name: restaurante_gestion_enseru
description: "App Web de Gestión Integral para Restaurante Enseru (DAM Hito 3)."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4

  # Utilidades
  intl: ^0.20.2          # Formateo de fechas/horas (turnos, regla 24 h)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
